### ISSUE TITLE
I cannot get the tap index when the index is equal to the active index

### ISSUE THREAD

**Issue by soleysok** [craiglabenz/flutter_rolling_nav_bar#4]
I think this is the cause. Could you help me out on this by creating another option to solve this problem
<img width="379" alt="Screen Shot 2020-12-17 at 3 19 59 PM" src="https://user-images.githubusercontent.com/45871758/102461695-579d1700-407b-11eb-84f7-47a437b89048.png">

**Comment by craiglabenz** [comment]
Thanks for filing this issue! Can you describe a bit more about what you'd like to accomplish? I think my assumption writing that guard statement was that tapping on the active index should short-circuit, since the roller should already be in its target destination.

But I certainly could be remembering this incorrectly.

**Comment by soleysok** [comment]
When the index is active, it doesn't give the onTap the index so I can't refresh the ui. What I want to do is to be able to get the index even if the index is already active. Thank you!

**Comment by soleysok** [comment]
@craiglabenz For Example, on the newsfeed screen of the Facebook app, when you tap on the newsfeed tab(when it is already active) it will refresh the screen to its original state. But since the onTap function doesn't return the tap index when the index is already active, I can't refresh the state.
